-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg8fHsHsy9k7rYyw/9
Xq3eToj6Gb7kQ2MJJlgNoVB7Za2gCgYIKoZIzj0DAQehRANCAASW4AbH/WUMxTlW
zev6+CWnsJCUxMFJi2ErKFZg0H3c5CWdScTXiyFL8OCDRXBIRIWOEZuME/r2yoyY
cNVxT+Ex
-----END PRIVATE KEY-----